lexik_jwt_authentication:
    secret_key: '%env(resolve:JWT_SECRET_KEY)%'
    public_key: '%env(resolve:JWT_PUBLIC_KEY)%'
    pass_phrase: ''
    token_ttl: '%env(int:JWT_TOKEN_TTL)%'     

    token_extractors:
        authorization_header:
            enabled: true
            prefix: Bearer
        query_parameter:
            enabled: true
            name: token

    user_identity_field: email  # using email field
